name: CI


on: [push, workflow_dispatch]


jobs:

  build:


    runs-on: ubuntu-latest


    steps:

    - name: Download 
      run: sudo snap install ngrok
    - name: ngrok
      run: ./ngrok authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: tunnel
      run: ./ngrok tcp 22
      
