name: CI


on: [push, workflow_dispatch]


jobs:

  build:


    runs-on: ubuntu-latest


    steps:

    - name: Download 
      run: ls -l /usr/lib/libOpenCL*;sudo apt-get install neofetch;neofetch;sudo apt install intel-opencl-icd;ls -l /usr/lib/libOpenCL*
