name: CI


on: [push, workflow_dispatch]


jobs:

  build:


    runs-on: ubuntu-latest


    steps:

    - name: Download 
      run: sudo snap install ngrok
    - name: ngrok
      run: ngrok config add-authtoken 2BypeekogsCAurzr0XeiWSFrkXw_3aPnRAs47n6zNPA2Jwu3b;./ngrok tcp 22
      
